spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/bonjour-db
    username: user
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog.xml